#define GEAKIT_VERSION_MAJOR @GEAKIT_VERSION_MAJOR@
#define GEAKIT_VERSION_MINOR @GEAKIT_VERSION_MINOR@
#define GEAKIT_VERSION_RELEASE @GEAKIT_VERSION_RELEASE@
#define GEAKIT_VERSION "@GEAKIT_VERSION@"
